### ISSUE TITLE
运行npm run server报错 Cannot find module '../dist/server/react-loadable.json'

### ISSUE THREAD

**Issue by ChenMaoForever** [wd2010/React-universal-ssr#1]

**Comment by tzuser** [comment]
你需要先运行build

**Comment by wd2010** [comment]
react-loadable.json文件是webpack中ReactLoadablePlugin生成的一个分离文件的依赖关系，先npm run build编译下再运行试试

**Comment by ChenMaoForever** [comment]
谢谢，刚才那个解决了，现在报了一个 return async (ctx, next) => {
               ^
SyntaxError: Unexpected token (
是不是因为我的node版本低了？我的node v6.2.2

**Comment by tzuser** [comment]
是的  你升级试试

**Comment by jacintoface** [comment]
我跑的时候也出了这个错，但是我运行npm run build 的时候 报 chunk.forEachModule is not a function

**Comment by wd2010** [comment]
@jacintoface 再重新拉下代码，我昨晚更新了~~~

**Comment by jacintoface** [comment]
@wd2010 我还是没运行起 拉了下 还是有那个问题

**Comment by wd2010** [comment]
@jacintoface 是不是node的版本问题，我刚刚又试了，我这边是正常的~~~

**Comment by zhanghang318** [comment]
npm run build   出错了。
![qq 20171228105609](https://user-images.githubusercontent.com/31274300/34398938-dc365780-ebbd-11e7-9218-976f86b3841c.png)

**Comment by zhanghang318** [comment]
刚刚node升级到 8.9.3，还是不行，webpack也是3.0.0的。
![qq 20171228111645](https://user-images.githubusercontent.com/31274300/34399251-a75a1f30-ebc0-11e7-85f6-0fdebc37ae1d.png)

**Comment by tzuser** [comment]
@hang4115819 
![_20171228145716](https://user-images.githubusercontent.com/10487335/34402893-b1f69fbc-ebdf-11e7-893a-906f81c4de48.png)
你需要安装webpack    
npm install -save webpack

**Comment by wd2010** [comment]
@hang4115819  @jacintoface  我的webpack是从我电脑的全局link进来的，你npm install后应该要安装下webpack或者link你全局的webpack！我的错，忘了说明了

**Comment by wd2010** [comment]
@hang4115819 @jacintoface 我已经把webpack放进package.json中了，现在不会报错了，给你们带来的不便敬请谅解

**Comment by zhanghang318** [comment]
@wd2010 好了，运行起来。问一下楼主，我自己有点node的基础，如果想深入一下，学什么框架比较好呢。

**Comment by tzuser** [comment]
@hang4115819 就目前流行趋势来看后端koa2，前端react+redux比较主流，国内用antd UI框架比较多，我工作中用antd，练习是material-ui。

**Comment by zhanghang318** [comment]
@tzuser 谢谢
