### ISSUE TITLE
启动 npm run server之后，看到network返回的并不是html结构的代码?

### ISSUE THREAD

**Issue by Snnny** [wd2010/React-universal-ssr#6]
结果跟npm start开发的时候一样，这是怎么回事？

**Comment by wd2010** [comment]
你先编译了吗？ npm run build

**Comment by Snnny** [comment]
是的，运行了。你确定 npm run build npm run server 之后 network能看到koa渲染之后的html结构？
顺便问一下，在你的项目里使用css module？
import  style from '../assets/css/my.scss'
console.log('>>>>>>>>>>>style', style) 像这样 style一直是一个空对象？ 我需要配置什么东西吗？

**Comment by wd2010** [comment]
是有html的呢
[
![a](https://user-images.githubusercontent.com/16284915/37253760-f1a96912-2570-11e8-9126-d4ed85803293.png)
](url)


另外你要输出style的那个是css-module吧，我这边没有用那个，我在后面是用的styled-components，也是一种css in js的写法，你可以试试
