### ISSUE TITLE
有没有考虑过引入dva来代替原有的redux项目

### ISSUE THREAD

**Issue by Mr-try** [wd2010/React-universal-ssr#8]
这个我参考这个项目在client端引入的dva
https://github.com/Mr-try/ssr，
对于服务端的引入有什么好的方式么？进一步的在server里面想要进行跟过的node操作，比如权限，数据库连接等有什么工程化的实例或者好的建议么

**Comment by wd2010** [comment]
dva这个我没用过，但用过rematch，应该是借鉴dva，对redux的简化~~~我前端时间有做一个基于React-universal-ssr这个脚手架的demo [https://github.com/wd2010/Material-ui-app](https://github.com/wd2010/Material-ui-app) 是用material-ui做ui，服务端用mongodb+GraphQL，我觉得实践下会对mongodb有一些理解，你可以参考下，希望对你有帮助！

**Comment by tzuser** [comment]
@Mr-try 有兴趣可以看看我正在写的这个基于antd-mobile的dome [https://github.com/tzuser/ant-mobile-base](https://github.com/tzuser/ant-mobile-base) ，如果和nodejs交互可以看看[https://github.com/tzuser/react-graphql](https://github.com/tzuser/react-graphql) 但是是使用graphql。
